# Generated by Django 2.0.4 on 2018-05-17 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(default=datetime.datetime.today, upload_to=''),
        ),
    ]
