# Generated by Django 2.0.4 on 2018-05-17 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0002_auto_20180516_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
